/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.simonsystem.doppelkeks;

import java.util.Arrays;

public class Doppelkeks {
    public static String convertIntegerToString(int value, String alphabet) {
        return "ABCD";
    }

    public static int convertStringToInteger(String value, String alphabet) {
        return 1234;
    }

    public static void main(String[] args) {
        // Read command line arguments or supply default values
        String value = args.length > 0 ? args[0] : "1111";
        String inAlphabet = args.length > 1 ? args[1] : "0123456789";
        String outAlphabet = args.length > 2 ? args[2] : "0123456789ABCDEF";

        // Convert value to integer and back to string, using the given basises
        int temp = Doppelkeks.convertStringToInteger(value, inAlphabet);
        String result = Doppelkeks.convertIntegerToString(temp, outAlphabet);

        // Print and exit
        System.out.println(result);
    }
}
