/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package doppelkeks;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test public void testAppCanCovertStringToInteger() {
        assertEquals(1111, App.convertStringToInteger("1111", 10, "0123456789"), "app should convet string to integer");
    }
    @Test public void testAppCanCovertIntegerToString() {
        assertEquals("1234", App.convertIntegerToString(1234, 10, "0123456789"), "app should convert integer to string");
    }
}
