/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package doppelkeks;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test public void testAppCanConvertStringToInteger() {
        assertEquals(1111, App.convertStringToInteger("1111", "0123456789"), "app should convert string to integer");
    }
    @Test public void testAppCanConvertIntegerToString() {
        assertEquals("1234", App.convertIntegerToString(1234, "0123456789"), "app should convert integer to string");
    }
}
